{{- $svcType := .Values.web.service.type | default "NodePort" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if and (eq $svcType "LoadBalancer") .Values.web.service.annotations }}
  annotations:
    {{- toYaml .Values.web.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svcType }}
  ports:
  - name: http
    port: {{ .Values.web.service.port | default 7777 }}
    targetPort: 3000
    protocol: TCP
    {{- if and (eq $svcType "NodePort") .Values.web.service.nodePort }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  selector:
    {{- include "tagent.selectorLabels" (dict "Release" .Release "component" "web") | nindent 4 }}
