"""Knowledge Base — pgvector-powered incident memory.

Stores past incidents as vector embeddings for:
1. Similar incident retrieval (cosine similarity)
2. Resolution pattern learning
3. Fix recommendation from history
4. Deduplication of known issues

Uses PostgreSQL + pgvector extension for vector similarity search.
Embeddings generated by local Ollama (nomic-embed-text model).
"""

import json
import os

# PostgreSQL with pgvector
DATABASE_URL = os.getenv("DATABASE_URL", "")
MONITORING_URL = os.getenv("MONITORING_URL", "http://localhost:8082")
REMEDIATION_URL = os.getenv("REMEDIATION_URL", "http://localhost:8084")

# We use asyncpg for async PostgreSQL access
_pool = None


async def get_pool():
    """Get or create the asyncpg connection pool."""
    global _pool
    if _pool is not None:
        return _pool

    if not DATABASE_URL:
        return None

    try:
        import asyncpg
        _pool = await asyncpg.create_pool(DATABASE_URL, min_size=2, max_size=5)
        await _init_schema(_pool)
        return _pool
    except Exception as e:
        print(f"[knowledge] PostgreSQL connection failed: {e}")
        return None


async def _init_schema(pool):
    """Create pgvector extension and knowledge tables."""
    async with pool.acquire() as conn:
        await conn.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS knowledge_entries (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                category TEXT NOT NULL,
                description TEXT NOT NULL,
                root_cause TEXT NOT NULL,
                fix_action TEXT NOT NULL,
                severity TEXT NOT NULL,
                service TEXT NOT NULL,
                namespace TEXT NOT NULL,
                occurrence_count INTEGER NOT NULL DEFAULT 1,
                success_rate REAL NOT NULL DEFAULT 0.0,
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                tags TEXT[] NOT NULL DEFAULT '{}',
                metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
            );

            CREATE INDEX IF NOT EXISTS idx_knowledge_embedding
                ON knowledge_entries USING ivfflat (embedding vector_cosine_ops)
                WITH (lists = 10);

            CREATE INDEX IF NOT EXISTS idx_knowledge_category
                ON knowledge_entries (category);

            CREATE INDEX IF NOT EXISTS idx_knowledge_service
                ON knowledge_entries (service);

            CREATE INDEX IF NOT EXISTS idx_knowledge_last_seen
                ON knowledge_entries (last_seen_at DESC);
        """)
    print("[knowledge] Schema initialized (pgvector enabled)")


async def store_entry(
    entry_id: str,
    title: str,
    category: str,
    description: str,
    root_cause: str,
    fix_action: str,
    severity: str,
    service: str,
    namespace: str,
    tags: list[str],
    embedding: list[float],
    metadata: dict | None = None,
) -> bool:
    """Store a knowledge entry with its vector embedding."""
    pool = await get_pool()
    if pool is None:
        return False

    async with pool.acquire() as conn:
        # Check if similar entry exists (by title match)
        existing = await conn.fetchrow(
            "SELECT id, occurrence_count FROM knowledge_entries WHERE title = $1",
            title
        )

        if existing:
            # Update existing entry (increment count, update last_seen)
            await conn.execute("""
                UPDATE knowledge_entries
                SET occurrence_count = occurrence_count + 1,
                    last_seen_at = now(),
                    updated_at = now(),
                    embedding = $2::vector
                WHERE id = $1
            """, existing["id"], str(embedding))
            return True

        # Insert new entry
        await conn.execute("""
            INSERT INTO knowledge_entries
                (id, title, category, description, root_cause, fix_action,
                 severity, service, namespace, tags, embedding, metadata)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::vector, $12::jsonb)
        """, entry_id, title, category, description, root_cause, fix_action,
            severity, service, namespace, tags, str(embedding),
            json.dumps(metadata or {}))
        return True


async def search_similar(embedding: list[float], limit: int = 5, threshold: float = 0.7) -> list[dict]:
    """Find similar incidents using cosine similarity on embeddings."""
    pool = await get_pool()
    if pool is None:
        return []

    async with pool.acquire() as conn:
        rows = await conn.fetch("""
            SELECT id, title, category, description, root_cause, fix_action,
                   severity, service, namespace, occurrence_count, success_rate,
                   last_seen_at, first_seen_at, tags, metadata,
                   1 - (embedding <=> $1::vector) as similarity
            FROM knowledge_entries
            WHERE embedding IS NOT NULL
            ORDER BY embedding <=> $1::vector
            LIMIT $2
        """, str(embedding), limit)

        results = []
        for row in rows:
            sim = float(row["similarity"])
            if sim >= threshold:
                results.append({
                    "id": row["id"],
                    "title": row["title"],
                    "category": row["category"],
                    "description": row["description"],
                    "root_cause": row["root_cause"],
                    "fix_action": row["fix_action"],
                    "severity": row["severity"],
                    "service": row["service"],
                    "namespace": row["namespace"],
                    "occurrence_count": row["occurrence_count"],
                    "success_rate": float(row["success_rate"]),
                    "last_seen_at": row["last_seen_at"].isoformat(),
                    "first_seen_at": row["first_seen_at"].isoformat(),
                    "tags": list(row["tags"]),
                    "metadata": json.loads(row["metadata"]) if row["metadata"] else {},
                    "similarity": round(sim, 4),
                })
        return results


async def get_all_entries(limit: int = 100, category: str | None = None) -> list[dict]:
    """Get all knowledge entries, optionally filtered by category."""
    pool = await get_pool()
    if pool is None:
        return []

    async with pool.acquire() as conn:
        if category:
            rows = await conn.fetch("""
                SELECT id, title, category, description, root_cause, fix_action,
                       severity, service, namespace, occurrence_count, success_rate,
                       last_seen_at, first_seen_at, tags, metadata
                FROM knowledge_entries
                WHERE category = $1
                ORDER BY occurrence_count DESC, last_seen_at DESC
                LIMIT $2
            """, category, limit)
        else:
            rows = await conn.fetch("""
                SELECT id, title, category, description, root_cause, fix_action,
                       severity, service, namespace, occurrence_count, success_rate,
                       last_seen_at, first_seen_at, tags, metadata
                FROM knowledge_entries
                ORDER BY occurrence_count DESC, last_seen_at DESC
                LIMIT $1
            """, limit)

        return [
            {
                "id": row["id"],
                "title": row["title"],
                "category": row["category"],
                "description": row["description"],
                "root_cause": row["root_cause"],
                "fix_action": row["fix_action"],
                "severity": row["severity"],
                "service": row["service"],
                "namespace": row["namespace"],
                "occurrence_count": row["occurrence_count"],
                "success_rate": float(row["success_rate"]),
                "last_seen_at": row["last_seen_at"].isoformat(),
                "first_seen_at": row["first_seen_at"].isoformat(),
                "tags": list(row["tags"]),
                "metadata": json.loads(row["metadata"]) if row["metadata"] else {},
            }
            for row in rows
        ]


async def get_stats() -> dict:
    """Get knowledge base statistics."""
    pool = await get_pool()
    if pool is None:
        return {"total_entries": 0, "categories": {}, "top_services": []}

    async with pool.acquire() as conn:
        total = await conn.fetchval("SELECT COUNT(*) FROM knowledge_entries")
        categories = await conn.fetch(
            "SELECT category, COUNT(*) as count FROM knowledge_entries GROUP BY category ORDER BY count DESC"
        )
        top_services = await conn.fetch(
            "SELECT service, COUNT(*) as count, SUM(occurrence_count) as total_occurrences FROM knowledge_entries GROUP BY service ORDER BY total_occurrences DESC LIMIT 10"
        )

        return {
            "total_entries": total,
            "categories": {row["category"]: row["count"] for row in categories},
            "top_services": [
                {"service": row["service"], "entries": row["count"], "total_occurrences": row["total_occurrences"]}
                for row in top_services
            ],
        }


async def update_success_rate(entry_id: str, success: bool) -> bool:
    """Update the success rate of a fix action after execution."""
    pool = await get_pool()
    if pool is None:
        return False

    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT occurrence_count, success_rate FROM knowledge_entries WHERE id = $1",
            entry_id
        )
        if not row:
            return False

        count = row["occurrence_count"]
        current_rate = float(row["success_rate"])
        # Running average
        new_rate = ((current_rate * (count - 1)) + (1.0 if success else 0.0)) / count

        await conn.execute(
            "UPDATE knowledge_entries SET success_rate = $1, updated_at = now() WHERE id = $2",
            new_rate, entry_id
        )
        return True
